### ISSUE TITLE
Todolist

### ISSUE THREAD

**Issue by xswzaq44321** [xswzaq44321/Ourcraft#1]
1. Prefab (5%)
- [x] Use prefab to instantiate objects (2%) Weber
- [x] Use different prefabs as your ground (3%) Chen
2. Collision (3%)
- [x] Character (1%) Chen
- [x] Monster (2%) Weber
3. 
- [x] Use a trigger as a sensor (2%) Chen
4. A completed start menu (3%)
- [x] Start a new game (1%) Weber
- [x] Exit your application (1%) Weber
- [x] There is a way to come back to game menu in game scene (1%) Chen
5. Output (5%)
- [x] Output as an application (exe file and those related files) (3%) 
- [x] It can work (2%) Both
6. Animation (10%)
- [x] Basic animation (3%) Weber
- [x] Advanced animation (mentioned in class) (7%) Weber
7. Controller (15%)
- [x] Gather some materials in scene (5%) Chen
- [x] Build / put your items(materials) in scene (10%) Chen
8. Music (6%)
- [x] Bgm (2%) Weber
- [x] Audio effects (4%) Weber->Player, Chen->Monster
9. Monster (5%)
- [x] Monster will turn up in night and attack to player   Weber
10. Game flow (20%)
- [x] Day and night mechanism(5%) Chen
- [x] Inventory system (15%) Chen
11. UI design (8%)
- [x] The start menu mentioned above
- [x] Inventory UI(8%) Chen
12.
- [x] Game map design (5%) Both

13. 
- [x] An interface that introduces how to play your game (5%) Chen
14. 
- [x] A detailed documentation to illustrate (8%) Both

> How to play your game
> Environment
> Your game
> Game design (how to design your character, monster, etc.)
> Bonus
> Feedback

**Comment by xswzaq44321** [comment]
- [x] 遊戲中退回選取畫面的按鈕

**Comment by IzsKon** [comment]
- [x]  設定時間速度 time.cs delta_time
- [x] 設定player走路、跑步速度 Controller.cs walk_speed runs_speed
- [x] 設定無限方塊 Backpack.cs infinity_block
- [x] 設定回復速度 Controller.cs  heal_speed
- [x] 設定降雨 Weather.cs public void rain(float last_time, uint heavy) (已經寫好了)
- [x] 設定降雨機率 Weather.cs raining_rate
- [x] 顯示降雨-開始時間 停止時間 雨量(顯示在LuaConsole上，可以嗎?) Weather.cs rain_start, rain_end rainfall
- [x] 設定攻擊距離 Controller.cs atk_range
- [x] 設定操作方塊距離 Backpack.cs touchable_distance
